### ISSUE TITLE
LaTeX error "Misplaced omit"

### ISSUE THREAD

**Issue by s-kilian** [imbi-heidelberg/DescrTab2#2]
I tried to create a descriptive table within an imbiReport2::imbi_report_tex Markdown document with the following chunk:

```{r, results='asis'}

# Create data frame with 20 variables
df <- data.frame(
  "x1" = 1:10
)

for(i in 2:20){
  df[[paste0("x", i)]] <- 1:10
}

# Print desription table
df %>%
  descr()

```

The dataset has 20 variables. When compiling the TeX document, it gives the following error:

! Misplaced \omit.
\multispan ->\omit 
                   \@multispan 
l.296 ...erscript{tt1} Students one-sample t-test}
                                                 \\ \\*

It seems to be caused by a double star (look for \\\\** in the TeX document) in the longtable environment. When deleting the second star manually in the TeX document, it can be compiled.
Interestingly, this error only occurs for a certain amount of variables/size of table. With 19 and 21 variables, everything works fine. The problem occurs again for 40 variables.

**Comment by jan-imbi** [comment]
It's fixed now. Bug was probably due to a "feature" in kableExtra, don't really understand it though.
